package main

import (
	"math/rand"

	"github.com/fogleman/gg"
)

func drawRandomArt(dc *gg.Context, seed int64) {
	rand.Seed(seed)
	for i := 0; i < 10; i++ {
		x := rand.Float64() * float64(dc.Width())
		y := rand.Float64() * float64(dc.Height())
		r := rand.Float64() * 0.5 * float64(dc.Width())
		dc.DrawCircle(x, y, r)
		dc.SetRGB(rand.Float64(), rand.Float64(), rand.Float64())
		dc.Fill()

	}
}

func handler(w http.ResponseWriter, r *http.Request) {
	dc := gg.NewContext(800, 800)
	hostname, _ := os.Hostname()
	seed := time.Now().UnixNano() + int64(hostname[0])
	drawRandomArt(dc, seed)
	if err := dc.LoadFontFace("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 100); err != nil {
		fmt.Println("Error loading font:", err)
	}
	dc.SetRGB(0, 0, 0) // Set text color to black
	dc.DrawStringAnchored(fmt.Sprintf("Generated by: %s", hostname), 400, 400, 0.5, 0.5)
	w.Header().Set("Content-Type", "image/png")
	dc.EncodePNG(w)
}

func main() {
	http.HandleFunc("/", handler)
	fmt.Println("Starting server on :8080")
	http.ListenAndServe(":8080", nil)
}
